repos:
-   repo: local
    hooks:
    -   id: tidy
        name: go mod tidy
        entry: /bin/bash go mod tidy
        language: system
        types: [go, go-mod]
    -   id: test
        name: go test
        entry: /bin/bash go test ./...
        language: system
        types: [go, go-mod]
